name: creative_fabrica
description: The test task for Creative Fabric company.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  #BLoC
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2

  #Firebase
  firebase_core: ^2.13.1
  firebase_auth: ^4.6.2

  #Network
  dio: ^5.2.0
  retrofit: ^4.0.1

  #Tools
  equatable: ^2.0.5
  json_annotation: ^4.8.1
  cached_network_image: ^3.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^9.1.3
  build_runner: ^2.4.4
  flutter_lints: ^2.0.1
  json_serializable: ^6.7.0
  retrofit_generator: ^7.0.1

flutter:
  uses-material-design: true